services:
  web:
    build: .
    working_dir: /src
    command: sh -c "rm -rf tmp/pids/server.pid && yarn install & bin/dev"
    volumes:
      - .:/src
    ports:
      - "3000:3000"
    env_file:
      - rails.env
      - twitter.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    stdin_open: true
    tty: true

  db:
    image: postgres:15
    expose:
      - "5432"
    ports:
      - "5432:5432"
    env_file:
      - rails.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres
      interval: 2s
      timeout: 5s
      retries: 30

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  pg_data:
  redis_data:
